

/* Generated by the NeXT Interface Builder */

#import "Control.h"

@interface NXColorSlider : Control
{
	int dist,units,start_color[4],end_color[4],ishueslider,enabled;
	NXRect track,knob;
	float value,oldvalue;
	NXSize cur;
	id _target;
	SEL _action;
	NXColor sovercolor;
	int soverslider;
	char *colortitle;
	float titlegray;
	id valueField;
	id bitmap;
	int textwidth;
	// put instance variables concerning state of selection
}

+ newFrame:(NXRect const *)theFrame;
- initFrame:(NXRect const *)theFrame;
- setEnabled:(BOOL)flag;
- setTitle:(char *)tit;
- setTextWidth:(int)tw;
- setTitleColor:(float)col;
- setHSBSlider:(int)ishue;
- setSoverSlider:(int)isit:(NXColor *)thecolor;
- resize:(NXRect *)newRect;
- renderGradation:(int *)start:(int *)end:(NXRect *)fr:(float)endbuf:(int)type;
- renderBitmap:(const NXRect *)theFrame;
- setGradation:(int *)start:(int *)end;
- newGradation:(int *)start:(int *)end;
- (BOOL) acceptsFirstMouse;
- colorbitmap;
- drawSelf:(NXRect *)rects :(int)rectCount;
- setUnits:(int)un;
- blitSelf;
- (float)valueForMouseLocation:(NXPoint *)pt;
- knobRect:(NXRect *)kr forValue:(float)val;
- mouseDown:(NXEvent *)theEvent;
- (int)getIntColor;
- (float)getFloatColor;
- setIntColor:(int)col;
- setFloatColor:(float)col;


@end
