

/* Generated by the NeXT Interface Builder */

#import "Control.h"
#import "color.h"

#define NUMMODES 7
#define NUMSLIDERS 12

@interface NXColorPicker : Control
{
        int colormode,currentpalette,lastmode,showalpha,colormask;
	id swatchbitmap;
	NXColor color;
	BOOL continuous;
	NXRect swatch,viewRect;
	NXSize max;
	id _target;
	SEL _action;
	
	id modeView[NUMMODES];
	id sliders[NUMSLIDERS];
	id colorModeButtons,colorSwatchView,colorBoxView;
	id customColorButtons,customColorBrowser;
	id customPaletteDisplayView;
	id grayButtons,alphaButtons;
	id paletteView,customColors;
	id magnifyButton;
	
	id wheelView;
	id expertButton;
	id splitView,swatch1,swatch2;
	//put instance variables concerning state of selection
}

+ newFrame:(NXRect const *)theFrame;
- initFrame:(NXRect const *)theFrame;
- setShowAlpha:(BOOL)flag;
- (int)colorMode;
- drawSelf:(NXRect *)rects :(int)rectCount;
- (int)colorMask;
- setColorMask:(int)mask;
- setInitialColorMask:(int)mask;
- createColorWheelView;
- createCustomPaletteView;
- createCustomColorView;
- createRGBView;
- createHSBView;
- createCMYKView;
- createGrayView;
- setGray:sender;
- setAlpha:sender;
- setColorFromSlider:sender;
- setHueColor:sender;
- updateHueSlider:(int)hue;
- doSizeView:anObject:(NXRect *)fr;
- checkColorModeButtons:anObject;
- checkAlphaSlider:anObject;
- setMode:(int)mode;
- center:anObject;
- setColorMode:sender;
- setAndSendButDontDisplay:(NXColor)newcolor:(int)doit;
- setAndSendColorValues:(NXColor)newcolor:(int)doit;
- setColorValues:(NXColor)newcolor;
- newColor:sender;
- setColor:(NXColor)color;
- _setColor:(NXColor *)color;
- (NXColor)getColor;
- (NXColor)color;
- _getColor:(NXColor *)color;
- setContinuous:(BOOL)flag;
- updateColor:(int)doit;
- wheelView;
- updateCustomColorList;
- setCustomColorBrowser:anObject;

@end

