PRODUCT =
PRODUCTS = mig migcom

# These actions will be done first when building the .NEW product.
# If this is unnecessary leave it blank, but don't delete this.

$(PRODUCT).NEWfirst:

# The rest of the work is done by the standard common makefile
LOADLIBS = -lsys_s
MAKEINCDIR = /usr/local/lib/Makefiles
include $(MAKEINCDIR)/Makeinc.common
