| These pointers are declared in pointers.c.  They get filled in with a #init
| from the library specification file with the real values of their symbols.
| They are used here to make an indirect jmp to these routines.
.globl __libNeXT_objc_msgSend
.globl __libNeXT_objc_msgSendSuper
.globl __libNeXT_objc_getClass
.globl __libNeXT_objc_getMetaClass
.globl __libNeXT_bcopy
.globl __libNeXT__fixunsdfsi
.globl __libNeXT__fixdfsi

| These are the routines to make the indirect jumps.   These are needed because
| they can't be substituted by cpp (because they are generated by the compiler
| directly).   To use these routines the NeXT link editor function of aliasing
| a symbol to  another symbol is used.  So the symbols like _objc_msgSend
| are aliased to .libNeXT_objc_msgSend etc. all the calls to them get
| relocated to their aliases.  The real symbols (_objc_msgSend, etc) never
| appear in the target shared library.
	.text
.globl .libNeXT_objc_msgSend
.libNeXT_objc_msgSend:
	movel	__libNeXT_objc_msgSend, a0
	jmp	a0@

.globl .libNeXT_objc_msgSendSuper
.libNeXT_objc_msgSendSuper:
	movel	__libNeXT_objc_msgSendSuper, a0
	jmp	a0@

.globl .libNeXT_objc_getClass
.libNeXT_objc_getClass:
	movel	__libNeXT_objc_getClass, a0
	jmp	a0@

.globl .libNeXT_objc_getMetaClass
.libNeXT_objc_getMetaClass:
	movel	__libNeXT_objc_getMetaClass, a0
	jmp	a0@

.globl .libNeXT_bcopy
.libNeXT_bcopy:
	movel	__libNeXT_bcopy, a0
	jmp	a0@

.globl .libNeXT__fixunsdfsi
.libNeXT__fixunsdfsi:
	movel	__libNeXT__fixunsdfsi, a0
	jmp	a0@

.globl .libNeXT__fixdfsi
.libNeXT__fixdfsi:
	movel	__libNeXT__fixdfsi, a0
	jmp	a0@

