#ifdef SHLIB
/*
 * This file is only used when building a shared version of libNeXT.
 * It's purpose is to turn references to symbols not defined in the
 * library into indirect references, via a pointer that will be defined
 * in the library (see the file pointers.c).  These macros are expected
 * to be substituted for both the references and the declarations.  In
 * the case the user supplies the declaration (in his code or and include
 * file) the type for the pointer is declared when the macro is substitued.
 * The user MUST supply a declaration for each of these symbols he uses in
 * his code.
 *
 * MAJOR ASSUMPTION here is that the object files of this library are not
 * expected to be substituted by the user.  This means that the inter module
 * references are linked directly to each other and if the user attempted to
 * replace an object file he would get a multiply defined error.
 */
/* In crt0.o */
#define	NXArgc (*_libNeXT_NXArgc)
#define	NXArgv (*_libNeXT_NXArgv)

/* In libsys_s.a */
#ifndef SHLIB_MIG
#define	close(a) (*_libNeXT_close)(a)
#define	floor(a) (*_libNeXT_floor)(a)
#define	free(a) (*_libNeXT_free)(a)
#define	open(a,b,c) (*_libNeXT_open)(a,b,c)
#define	read(a,b,c) (*_libNeXT_read)(a,b,c)
#define select(a,b,c,d,e) (*_libNeXT_select)(a,b,c,d,e)
#define	sigvec(a,b,c) (*_libNeXT_sigvec)(a,b,c)
#define stat(a,b) (*_libNeXT_stat)(a,b)
#define	strcat(a,b) (*_libNeXT_strcat)(a,b)
#define	strncpy(a,b,c) (*_libNeXT_strncpy)(a,b,c)
#define	time(a) (*_libNeXT_time)(a)
#define wait(a) (*_libNeXT_wait)(a)
#define	write(a,b,c) (*_libNeXT_write)(a,b,c)
#else (defined SHLIB_MIG)
#define	close (*_libNeXT_close)
#define	floor (*_libNeXT_floor)
#define	free (*_libNeXT_free)
#define	open (*_libNeXT_open)
#define	read (*_libNeXT_read)
#define select (*_libNeXT_select)
#define	sigvec (*_libNeXT_sigvec)
#define stat (*_libNeXT_stat)
#define	strcat (*_libNeXT_strcat)
#define	strncpy (*_libNeXT_strncpy)
#define	time (*_libNeXT_time)
#define wait (*_libNeXT_wait)
#define	write (*_libNeXT_write)
#endif

#define NXAllocErrorData (*_libNeXT_NXAllocErrorData)
#define NXResetErrorData (*_libNeXT_NXResetErrorData)
#define NXClose (*_libNeXT_NXClose)
#define NXCloseMemory (*_libNeXT_NXCloseMemory)
#define NXCloseTypedStream (*_libNeXT_NXCloseTypedStream)
#define NXDefaultRead (*_libNeXT_NXDefaultRead)
#define NXDefaultWrite (*_libNeXT_NXDefaultWrite)
#define NXEndOfTypedStream (*_libNeXT_NXEndOfTypedStream)
#define NXFlush (*_libNeXT_NXFlush)
#define NXFlushTypedStream (*_libNeXT_NXFlushTypedStream)
#define NXFreeObjectBuffer (*_libNeXT_NXFreeObjectBuffer)
#define NXGetMemoryBuffer (*_libNeXT_NXGetMemoryBuffer)
#define NXMapFile (*_libNeXT_NXMapFile)
#define NXOpenFile (*_libNeXT_NXOpenFile)
#define NXOpenMemory (*_libNeXT_NXOpenMemory)
#define NXOpenTypedStream (*_libNeXT_NXOpenTypedStream)
#define NXOpenTypedStreamForFile (*_libNeXT_NXOpenTypedStreamForFile)
#define NXPrintf (*_libNeXT_NXPrintf)
#define NXReadArray (*_libNeXT_NXReadArray)
#define NXReadClass (*_libNeXT_NXReadClass)
#define NXReadObject (*_libNeXT_NXReadObject)
#define NXReadObjectFromBuffer (*_libNeXT_NXReadObjectFromBuffer)
#define NXReadType (*_libNeXT_NXReadType)
#define NXReadTypes (*_libNeXT_NXReadTypes)
#define NXSaveToFile (*_libNeXT_NXSaveToFile)
#define NXScanf (*_libNeXT_NXScanf)
#define NXSeek (*_libNeXT_NXSeek)
#define NXSetTypedStreamZone (*_libNeXT_NXSetTypedStreamZone)
#define NXStreamCreate (*_libNeXT_NXStreamCreate)
#define NXStreamCreateFromZone (*_libNeXT_NXStreamCreateFromZone)
#define NXSystemVersion (*_libNeXT_NXSystemVersion)
#define NXTell (*_libNeXT_NXTell)
#define NXUngetc (*_libNeXT_NXUngetc)
#define NXVPrintf (*_libNeXT_NXVPrintf)
#define NXWriteArray (*_libNeXT_NXWriteArray)
#define NXWriteClass (*_libNeXT_NXWriteClass)
#define NXWriteObject (*_libNeXT_NXWriteObject)
#define NXWriteObjectReference (*_libNeXT_NXWriteObjectReference)
#define NXWriteRootObject (*_libNeXT_NXWriteRootObject)
#define NXWriteRootObjectToBuffer (*_libNeXT_NXWriteRootObjectToBuffer)
#define NXWriteType (*_libNeXT_NXWriteType)
#define NXWriteTypes (*_libNeXT_NXWriteTypes)

#define NXCreateZone (*_libNeXT_NXCreateZone)
#define NXCreateChildZone (*_libNeXT_NXCreateChildZone)
#define NXMergeZone (*_libNeXT_NXMergeZone)
#define NXZoneCalloc (*_libNeXT_NXZoneCalloc)
#define NXZoneFromPtr (*_libNeXT_NXZoneFromPtr)
#define NXZonePtrInfo (*_libNeXT_NXZonePtrInfo)
#define NXDefaultMallocZone (*_libNeXT_NXDefaultMallocZone)
#define NXNameZone (*_libNeXT_NXNameZone)

#define SNDAlloc (*_libNeXT_SNDAlloc)
#define SNDBytesToSamples (*_libNeXT_SNDBytesToSamples)
#define SNDCompactSamples (*_libNeXT_SNDCompactSamples)
#define SNDConvertSound (*_libNeXT_SNDConvertSound)
#define SNDCopySamples (*_libNeXT_SNDCopySamples)
#define SNDCopySound (*_libNeXT_SNDCopySound)
#define SNDDeleteSamples (*_libNeXT_SNDDeleteSamples)
#define SNDFree (*_libNeXT_SNDFree)
#define SNDGetMute (*_libNeXT_SNDGetMute)
#define SNDGetVolume (*_libNeXT_SNDGetVolume)
#define SNDInsertSamples (*_libNeXT_SNDInsertSamples)
#define SNDMulaw (*_libNeXT_SNDMulaw)
#define SNDReadSoundfile (*_libNeXT_SNDReadSoundfile)
#define SNDSampleCount (*_libNeXT_SNDSampleCount)
#define SNDSamplesProcessed (*_libNeXT_SNDSamplesProcessed)
#define SNDSetMute (*_libNeXT_SNDSetMute)
#define SNDSetVolume (*_libNeXT_SNDSetVolume)
#define SNDStartPlaying (*_libNeXT_SNDStartPlaying)
#define SNDStartRecording (*_libNeXT_SNDStartRecording)
#define SNDStop (*_libNeXT_SNDStop)
#define SNDWait (*_libNeXT_SNDWait)
#define SNDWriteSoundfile (*_libNeXT_SNDWriteSoundfile)
#define SNDiMulaw (*_libNeXT_SNDiMulaw)

#define _NXAddHandler (*_libNeXT__NXAddHandler)
#define _NXRaiseError (*_libNeXT__NXRaiseError)
#define _NXRemoveHandler (*_libNeXT__NXRemoveHandler)
#define _NXStreamChangeBuffer (*_libNeXT__NXStreamChangeBuffer)
#define _NXStreamFillBuffer (*_libNeXT__NXStreamFillBuffer)
#define _NXStreamFlushBuffer (*_libNeXT__NXStreamFlushBuffer)
#define _NXUncaughtExceptionHandler (*_libNeXT__NXUncaughtExceptionHandler)
#define _alloc (*_libNeXT__alloc)
#define _zoneAlloc (*_libNeXT__zoneAlloc)
#define _ctype_ (*_libNeXT__ctype_)
#define _cvtToId (*_libNeXT__cvtToId)
#define _cvtToSel (*_libNeXT__cvtToSel)
#define _error (*_libNeXT__error)
#define _filbuf (*_libNeXT__filbuf)
#define _flsbuf (*_libNeXT__flsbuf)
#define _freedName (*_libNeXT__freedName)
#define _iob (*_libNeXT__iob)
#define _longjmp (*_libNeXT__longjmp)
#define _mh_execute_header (*_libNeXT__mh_execute_header)
#define _nilName (*_libNeXT__nilName)
#define _setjmp (*_libNeXT__setjmp)
#define _strhash (*_libNeXT__strhash)
#define abort (*_libNeXT_abort)
#define abs (*_libNeXT_abs)
#define access (*_libNeXT_access)
#define alarm (*_libNeXT_alarm)
#define alphasort (*_libNeXT_alphasort)
#define atoi (*_libNeXT_atoi)
#define bootstrap_look_up (*_libNeXT_bootstrap_look_up)
#define ceil (*_libNeXT_ceil)
#define chdir (*_libNeXT_chdir)
#define chown (*_libNeXT_chown)
#define closedir (*_libNeXT_closedir)
#define connect (*_libNeXT_connect)
#define cthread_detach (*_libNeXT_cthread_detach)
#define cthread_fork (*_libNeXT_cthread_fork)
#define cthread_init (*_libNeXT_cthread_init)
#define cthread_name (*_libNeXT_cthread_name)
#define cthread_set_name (*_libNeXT_cthread_set_name)
#define ctime (*_libNeXT_ctime)
#define dbClose (*_libNeXT_dbClose)
#define dbCreate (*_libNeXT_dbCreate)
#define dbDelete (*_libNeXT_dbDelete)
#define dbExists (*_libNeXT_dbExists)
#define dbFetch (*_libNeXT_dbFetch)
#define dbInit (*_libNeXT_dbInit)
#define dbOpen (*_libNeXT_dbOpen)
#define dbStore (*_libNeXT_dbStore)
#define dbUnlock (*_libNeXT_dbUnlock)
#define dbWaitLock (*_libNeXT_dbWaitLock)
#define endpwent (*_libNeXT_endpwent)
#define errno (*_libNeXT_errno)
#define execl (*_libNeXT_execl)
#define execv (*_libNeXT_execv)
#define exit (*_libNeXT_exit)
#define fclose (*_libNeXT_fclose)
#define fcntl (*_libNeXT_fcntl)
#define fflush (*_libNeXT_fflush)
#define fgets (*_libNeXT_fgets)
#define fopen (*_libNeXT_fopen)
#define fork (*_libNeXT_fork)
#define fprintf (*_libNeXT_fprintf)
#define fread (*_libNeXT_fread)
#define fseek (*_libNeXT_fseek)
#define fstat (*_libNeXT_fstat)
#define ftruncate (*_libNeXT_ftruncate)
#define fwrite (*_libNeXT_fwrite)
#define getdtablesize (*_libNeXT_getdtablesize)
#define getenv (*_libNeXT_getenv)
#define getegid (*_libNeXT_getegid)
#define geteuid (*_libNeXT_geteuid)
#define gethostbyname (*_libNeXT_gethostbyname)
#define gethostname (*_libNeXT_gethostname)
#define getlogin (*_libNeXT_getlogin)
#define getpid (*_libNeXT_getpid)
#define getpwent (*_libNeXT_getpwent)
#define getpwnam (*_libNeXT_getpwnam)
#define getpwuid (*_libNeXT_getpwuid)
#define getrusage (*_libNeXT_getrusage)
#define getsectbyname (*_libNeXT_getsectbyname)
#define getsectbynamefromheader (*_libNeXT_getsectbynamefromheader)
#define getsectdata (*_libNeXT_getsectdata)
#define getsectdatafromheader (*_libNeXT_getsectdatafromheader)
#define getsectdatafromlib (*_libNeXT_getsectdatafromlib)
#define gettimeofday (*_libNeXT_gettimeofday)
#define getgid (*_libNeXT_getgid)
#define getuid (*_libNeXT_getuid)
#define getwd (*_libNeXT_getwd)
#define ioctl (*_libNeXT_ioctl)
#define link (*_libNeXT_link)
#define longjmp (*_libNeXT_longjmp)
#define lseek (*_libNeXT_lseek)
#define lstat (*_libNeXT_lstat)
#define mach_error (*_libNeXT_mach_error)
#define mach_error_string (*_libNeXT_mach_error_string)
#define mach_ports_lookup (*_libNeXT_mach_ports_lookup)
#define mach_ports_register (*_libNeXT_mach_ports_register)
#define malloc(a) (*_libNeXT_malloc)(a)
#define malloc_error (*_libNeXT_malloc_error)
#define malloc_debug (*_libNeXT_malloc_debug)
#define map_fd (*_libNeXT_map_fd)
#define memcmp (*_libNeXT_memcmp)
#define memmove (*_libNeXT_memmove)
#define memset (*_libNeXT_memset)
#define mig_dealloc_reply_port (*_libNeXT_mig_dealloc_reply_port)
#define mig_get_reply_port (*_libNeXT_mig_get_reply_port)
#define mkdir (*_libNeXT_mkdir)
#define moncontrol (*_libNeXT_moncontrol)
#define msg_receive (*_libNeXT_msg_receive)
#define msg_rpc (*_libNeXT_msg_rpc)
#define msg_send (*_libNeXT_msg_send)
#define mstats (*_libNeXT_mstats)
#define mutex_try_lock (*_libNeXT_mutex_try_lock)
#define mutex_wait_lock (*_libNeXT_mutex_wait_lock)
#define name_server_port (*_libNeXT_name_server_port)
#define netname_check_in (*_libNeXT_netname_check_in)
#define netname_check_out (*_libNeXT_netname_check_out)
#define netname_look_up (*_libNeXT_netname_look_up)
#define opendir (*_libNeXT_opendir)
#define pclose (*_libNeXT_pclose)
#define pipe (*_libNeXT_pipe)
#define popen (*_libNeXT_popen)
#define port_allocate (*_libNeXT_port_allocate)
#define port_deallocate (*_libNeXT_port_deallocate)
#define port_set_add (*_libNeXT_port_set_add)
#define port_set_allocate (*_libNeXT_port_set_allocate)
#define port_set_backlog (*_libNeXT_port_set_backlog)
#define port_set_deallocate (*_libNeXT_port_set_deallocate)
#define port_set_remove (*_libNeXT_port_set_remove)
#define port_status (*_libNeXT_port_status)
#define pow (*_libNeXT_pow)
#define prdb_end (*_libNeXT_prdb_end)
#define prdb_get (*_libNeXT_prdb_get)
#define prdb_getbyname (*_libNeXT_prdb_getbyname)
#define prdb_set (*_libNeXT_prdb_set)
#define printf (*_libNeXT_printf)
#define prnStack (*_libNeXT_prnStack)
#define qsort (*_libNeXT_qsort)
#define readdir (*_libNeXT_readdir)
#define realloc(a,b) (*_libNeXT_realloc)(a,b)
#define scandir (*_libNeXT_scandir)
#define seekdir (*_libNeXT_seekdir)
#define setpwent (*_libNeXT_setpwent)
#define signal (*_libNeXT_signal)
#define socket (*_libNeXT_socket)
#define sprintf (*_libNeXT_sprintf)
#define sscanf (*_libNeXT_sscanf)
#define strchr (*_libNeXT_strchr)
#define strcmp (*_libNeXT_strcmp)
#define strcpy (*_libNeXT_strcpy)
#define strlen (*_libNeXT_strlen)
#define strncat (*_libNeXT_strncat)
#define strncmp (*_libNeXT_strncmp)
#define strrchr (*_libNeXT_strrchr)
#define strtod (*_libNeXT_strtod)
#define strtok (*_libNeXT_strtok)
#define system (*_libNeXT_system)
#define task_notify (*_libNeXT_task_notify)
#define task_self_ (*_libNeXT_task_self_)
#define task_get_special_port (*_libNeXT_task_get_special_port)
#define task_set_special_port (*_libNeXT_task_set_special_port)
#define thread_abort (*_libNeXT_thread_abort)
#define thread_info (*_libNeXT_thread_info)
#define thread_policy (*_libNeXT_thread_policy)
#define thread_priority (*_libNeXT_thread_priority)
#define thread_self (*_libNeXT_thread_self)
#define umask (*_libNeXT_umask)
#define unlink (*_libNeXT_unlink)
#define valloc (*_libNeXT_valloc)
#define vfork (*_libNeXT_vfork)
#define vfprintf (*_libNeXT_vfprintf)
#define vm_allocate (*_libNeXT_vm_allocate)
#define vm_copy (*_libNeXT_vm_copy)
#define vm_deallocate (*_libNeXT_vm_deallocate)
#define vm_page_size (*_libNeXT_vm_page_size)
#define vm_protect (*_libNeXT_vm_protect)
#define wait3 (*_libNeXT_wait3)

/* must fix these up in spec_NeXT later */
#define NXCreateHashTable (*_libNeXT_NXCreateHashTable)
#define NXCreateHashTableFromZone (*_libNeXT_NXCreateHashTableFromZone)
#define NXFreeHashTable (*_libNeXT_NXFreeHashTable)
#define NXEmptyHashTable (*_libNeXT_NXEmptyHashTable)
#define NXCopyHashTable (*_libNeXT_NXCopyHashTable)
#define NXCountHashTable (*_libNeXT_NXCountHashTable)
#define NXHashMember (*_libNeXT_NXHashMember)
#define NXHashGet (*_libNeXT_NXHashGet)
#define NXHashInsert (*_libNeXT_NXHashInsert)
#define NXHashRemove (*_libNeXT_NXHashRemove)
#define NXInitHashState (*_libNeXT_NXInitHashState)
#define NXNextHashState (*_libNeXT_NXNextHashState)
#define NXPtrHash (*_libNeXT_NXPtrHash)
#define NXStrHash (*_libNeXT_NXStrHash)
#define NXPtrIsEqual (*_libNeXT_NXPtrIsEqual)
#define NXStrIsEqual (*_libNeXT_NXStrIsEqual)
#define NXNoEffectFree (*_libNeXT_NXNoEffectFree)
#define NXReallyFree (*_libNeXT_NXReallyFree)
#define NXUniqueString (*_libNeXT_NXUniqueString)
#define NXUniqueStringWithLength (*_libNeXT_NXUniqueStringWithLength)
#define NXUniqueStringNoCopy (*_libNeXT_NXUniqueStringNoCopy)
#define NXCopyStringBuffer (*_libNeXT_NXCopyStringBuffer)
#define NXCopyStringBufferFromZone (*_libNeXT_NXCopyStringBufferFromZone)
#define NXStrPrototype (*_libNeXT_NXStrPrototype)

#define sel_isMapped (*_libNeXT_sel_isMapped)
#define sel_getName (*_libNeXT_sel_getName)
#define sel_getUid (*_libNeXT_sel_getUid)
#define object_getClassName (*_libNeXT_object_getClassName)
#define object_setInstanceVariable (*_libNeXT_object_setInstanceVariable)

#define _NXAddAltHandler (*_libNeXT__NXAddAltHandler)
#define _NXRemoveAltHandler (*_libNeXT__NXRemoveAltHandler)
#define NXTypedStreamClassVersion (*_libNeXT_NXTypedStreamClassVersion)
#define vsprintf (*_libNeXT_vsprintf)

#define sleep(x) (*_libNeXT_sleep)(x)
#define usleep(x) (*_libNeXT_usleep)(x)
#define calloc (*_libNeXT_calloc)
#define kern_timestamp (*_libNeXT_kern_timestamp)

#define openlog (*_libNeXT_openlog)
#define syslog (*_libNeXT_syslog)
#define fputc (*_libNeXT_fputc)

#define snddriver_stream_start_reading (*_libNeXT_snddriver_stream_start_reading)
#define snddriver_stream_setup (*_libNeXT_snddriver_stream_setup)
#define snddriver_reply_handler (*_libNeXT_snddriver_reply_handler)
#define snddriver_stream_control (*_libNeXT_snddriver_stream_control)
#define snddriver_set_sndin_owner_port (*_libNeXT_snddriver_set_sndin_owner_port)

#define SNDBootDSP (*_libNeXT_SNDBootDSP)
#define snddriver_dsp_write (*_libNeXT_snddriver_dsp_write)
#define SNDReadDSPfile (*_libNeXT_SNDReadDSPfile)
#define snddriver_set_dsp_owner_port (*_libNeXT_snddriver_set_dsp_owner_port)
#define snddriver_get_dsp_cmd_port (*_libNeXT_snddriver_get_dsp_cmd_port)
#define snddriver_dsp_protocol (*_libNeXT_snddriver_dsp_protocol)

#define getdirentries (*_libNeXT_getdirentries)

#define atan(x) (*_libNeXT_atan)(x)
#define cos(x) (*_libNeXT_cos)(x)
#define sin(x) (*_libNeXT_sin)(x)
#define sqrt(x) (*_libNeXT_sqrt)(x)
#define fabs(x) (*_libNeXT_fabs)(x)

#define SNDStartRecordingFile (*_libNeXT_SNDStartRecordingFile)

#define setlocale (*_libNeXT_setlocale)

#define condition_wait (*_libNeXT_condition_wait)
#define cond_signal (*_libNeXT_cond_signal)

#define NXRegisterDefaults	(*_libNeXT_NXRegisterDefaults)
#define NXGetDefaultValue	(*_libNeXT_NXGetDefaultValue)
#define NXSetDefault		(*_libNeXT_NXSetDefault)
#define NXWriteDefault		(*_libNeXT_NXWriteDefault)
#define NXWriteDefaults		(*_libNeXT_NXWriteDefaults)
#define NXRemoveDefault		(*_libNeXT_NXRemoveDefault)
#define NXReadDefault		(*_libNeXT_NXReadDefault)
#define NXUpdateDefaults	(*_libNeXT_NXUpdateDefaults)
#define NXUpdateDefault		(*_libNeXT_NXUpdateDefault)
#define NXSetDefaultsUser	(*_libNeXT_NXSetDefaultsUser)
#define NXFilePathSearch	(*_libNeXT_NXFilePathSearch)
#define NXGetTempFilename	(*_libNeXT_NXGetTempFilename)

#define NXToLower	(*_libNeXT_NXToLower)
#define NXIsLower	(*_libNeXT_NXIsLower)
#define NXIsDigit	(*_libNeXT_NXIsDigit)
#define NXToAscii	(*_libNeXT_NXToAscii)

#else
#error shlib.h should never be used when not building shlibs!
#endif SHLIB
