#define CS_AID 1
#define CS_BOOT 1
#define CS_BUGFIX 1
#define CS_COMPAT 1
#define CS_CONS 1
#define CS_DISK 1
#define CS_GENERIC 1
#define CS_GFB 1
#define CS_ICHK 1
#define CS_INET 1
#define CS_IPC 1
#define CS_KDB 1
#define CS_LINT 1
#define CS_MSYS 0
#define CS_NOFILE 1
#define CS_OLDDIR 1
#define CS_OLDFS 1
#define CS_QUOTE 1
#define CS_QVSS 1
#define CS_REM 1
#define CS_RPAUSE 1
#define CS_SECURITY 1
#define CS_SOCKET 1
#define CS_SYSCALL 1
#define CS_TCP 1
#define CS_TTY 1
#define CS_TTYLOC 1
#define CS_VAXM 1
#define CS_XLDS 1
#define CS_XMOD 1
#define CS_XONLY 1
#define NCSS 0
#define WB_ACC 1
#define WB_HP 1
#define WB_LOAD 1
#define NWB_ML 0
#define WB_MP 1
#define NWB_MPM 4
#define WB_SHM 1
#define WB_SYSCALL 1
#define WB_TIME 1
