#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.1 (Berkeley) 6/7/85
#
# curses package
#

DSTDIR=
LIBDIR=$(DSTDIR)/usr/lib

CFILES=	addch.c addstr.c box.c clear.c clrtobot.c clrtoeol.c cr_put.c \
	cr_tty.c curses.c delch.c deleteln.c delwin.c endwin.c erase.c \
	fullname.c getch.c getstr.c idlok.c id_subwins.c initscr.c insch.c \
	insertln.c longname.c move.c mvprintw.c mvscanw.c mvwin.c newwin.c \
	overlay.c overwrite.c printw.c putchar.c refresh.c scanw.c scroll.c \
	toucholap.c standout.c touchwin.c tstp.c unctrl.c
OBJS=	addch.o addstr.o box.o clear.o clrtobot.o clrtoeol.o cr_put.o \
	cr_tty.o curses.o delch.o deleteln.o delwin.o endwin.o erase.o \
	fullname.o getch.o getstr.o idlok.o id_subwins.o initscr.o insch.o \
	insertln.o longname.o move.o mvprintw.o mvscanw.o mvwin.o newwin.o \
	overlay.o overwrite.o printw.o putchar.o refresh.o scanw.o scroll.o \
	toucholap.o standout.o touchwin.o tstp.o unctrl.o

CTAGS=	ctags
DEFS=
#CFLAGS=	-O $(DEFS)
CFLAGS= ${DEFS} -DNeXT_MOD -bsd
TAGSFILE=tags
MV= mv -f

all: libcurses libcurses_p

.c.o:
	${CC} -c -pg ${CFLAGS} $<
	ld -x -r $@ -o profiled/$@
	@rm -f $@
	${CC} -c ${CFLAGS} $<
	ld -x -r $@
	${MV} a.out $@

libcurses libcurses_p: ${OBJS}
	@echo building profiled libcurses
	@cd profiled; ar cu ../libcurses_p ${OBJS}
	ranlib libcurses_p
	@echo building normal libcurses
	@ar cu libcurses ${OBJS}
	ranlib libcurses

install: ckdstroot libcurses libcurses_p
	install -m 644 libcurses $(DSTROOT)/${LIBDIR}/libcurses.a
	ranlib $(DSTROOT)/${LIBDIR}/libcurses.a
	install -m 644 libcurses_p $(DSTROOT)/${LIBDIR}/libcurses_p.a
	ranlib $(DSTROOT)/${LIBDIR}/libcurses_p.a

local: cklclroot libcurses libcurses_p
	install -m 644 libcurses $(LCLROOT)/${LIBDIR}/libcurses.a
	ranlib $(LCLROOT)/${LIBDIR}/libcurses.a
	install -m 644 libcurses_p $(LCLROOT)/${LIBDIR}/libcurses_p.a
	ranlib $(LCLROOT)/${LIBDIR}/libcurses_p.a

ckdstroot:
	@if [ -n "${DSTROOT}" ]; then exit 0; \
	else echo Must define DSTROOT; exit 1; \
	fi

cklclroot:
	@if [ -n "${LCLROOT}" ]; then exit 0; \
	else echo Must define LCLROOT; exit 1; \
	fi

tags:
	cwd=`pwd`; \
	for i in ${CFILES}; do \
		ctags -a -f ${TAGSFILE} $$cwd/$$i; \
	done

clean:
	rm -f ${OBJS} profiled/*.o a.out core test errs \
	    libcurses libcurses_p tags

ctags:
	${CTAGS} ${CFILES} curses.h

lint:
	lint -hxb ${CFILES} -lcurses > lint.out

test:	libcurses test.o
	${CC} ${LDFLAGS} ${CFLAGS} -o test test.o libcurses -ltermlib

test.o:	test.c
	${CC} ${CFLAGS} -c test.c

ar:
	ar crv curses.ar ${CFILES} curses.h curses.ext Makefile

depend:
	@echo No depend target, make depend ignored
