#define NXCPos		info->layInfo.cache.curPos
#define NXCharA		info->layInfo.chars	
#define NXCurBlock	info->layInfo.cache.curBlock
#define NXCurRun 	info->layInfo.cache.curRun
#define NXEndsParagraph info->layInfo.lFlags.endsParagraph
#define NXLayA		info->layInfo.lays
#define NXLayErase	info->layInfo.lFlags.erase
#define NXLayHCanGrow 	info->layInfo.lFlags.horizCanGrow
#define NXLayRect	info->layInfo.rect
#define NXLayDescent	info->layInfo.descent
#define NXLayWidth	info->layInfo.width
#define NXLeft		info->layInfo.left
#define NXRFirstPos	info->layInfo.cache.runFirstPos
#define NXRight		info->layInfo.right
#define NXRightIndent	info->layInfo.rightIndent
#define NXTFirstPos	info->layInfo.cache.blockFirstPos
#define NXWidthA	info->layInfo.widths
#define NXXA		info->globals.xPos
#define _NXTextClipRect	info->globals.textClipRect
#define _NXTabs		info->globals.tabs
#define _NXTabsEnd	info->globals.tabsEnd
#define _NXTabsPending	info->globals.tabsPending
