/* 
 * Mach Operating System
 * Copyright (c) 1987 Carnegie-Mellon University
 * All rights reserved.  The CMU software License Agreement specifies
 * the terms and conditions for use and redistribution.
 */
/*
 * config.h
 *
 * $Source: /os/osdev/LIBS/libs-7/etc/nmserver/conf/RCS/config.h,v $
 *
 * $Header: config.h,v 1.1 88/09/30 17:44:21 osdev Exp $
 *
 */

/*
 * Special definitions controlling the configuration of the Network Server.
 */

/*
 * HISTORY:
 * 20-May-88  Mary Thompson (mrt) at Carnegie Mellon
 *	Added || (ns32000) to vax conditional in defining
 *	CONF_OWN_FORMAT
 *
 * 27-Feb-88  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Added COMPAT.
 *
 * 21-Feb-88  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Reorganized into user-settable and fixed switches.
 *
 * 14-Dec-87  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Added RPCMOD, CAMELOT, USE_TCP.
 *
 * 19-Aug-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Added PORTSTAT.
 *
 * 30-Jul-87  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Added NETPORT.
 *
 * 22-Jun-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Added USE_VMTP condition.
 *
 * 12-Jun-87  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Defined KERNEL_FEATURES.
 *
 *  8-Jun-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Added NM_USE_KDS condition - if on then start up and use a KDS.
 *
 * 19-May-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Added NM_STATISTICS condition - if on then statistics are gathered.
 *
 * 30-Apr-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Added LOCK_THREADS condition - if on only one thread can run at once.
 *
 * 16-Apr-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Only define debugging constants if they are not already defined.
 *
 * 13-Mar-87  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Added various debugging and tracing definitions.
 *
 *  6-Feb-87  Robert Sansom (rds) at Carnegie Mellon University
 *	Added conf_own_format - network order representation of CONF_OWN_FORMAT.
 *
 * 14-Dec-86  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Redefined the formats to be more general instead of having one
 *	for each machine type.
 *
 * 25-Nov-86  Robert Sansom (rds) at Carnegie Mellon University
 *	Moved src_format values from disp_hdr.h to here.
 *	Configure according to compiler preprocessor definitions.
 *
 * 15-Nov-86  Daniel Julin (dpj) at Carnegie-Mellon University
 *	Created.
 *
 */

#ifndef	_CONFIG_
#define	_CONFIG_

/*
 * Values for src_format
 */
#define DISP_FMT_NETWORK	0
#define DISP_FMT_VL_1		1	/* Vax order, long align */
#define DISP_FMT_NL_1		2	/* Non-vax order, long align */
#define DISP_FMT_MAX		(2 + 1)

/*
 * Format of the messages generated by servers on different machine types.
 */
#if defined ( vax ) || defined ( ns32000 )
#define	CONF_OWN_FORMAT		DISP_FMT_VL_1
#define	LongAlign		1
#define	VaxOrder		1
#endif vax || ns32000

#ifdef romp
#define CONF_OWN_FORMAT		DISP_FMT_NL_1
#define	LongAlign		1
#define	VaxOrder		0
#endif romp

#ifdef NeXT || sun
#define CONF_OWN_FORMAT		DISP_FMT_NL_1
#define	LongAlign		1
#define	VaxOrder		0
#endif NeXT || sun

extern short 			conf_own_format;

#define	KERNEL_FEATURES	1

#define	PROF		0


/*
 * The following are switches that should be set before compiling the network
 * server. See the Network Server Design Document for details.
 */

#ifndef	NET_LOG
#define	NET_LOG		1
#endif	NET_LOG
#ifndef	NET_DEBUG
#define	NET_DEBUG	1
#endif	NET_DEBUG
#ifndef	NET_TRACE
#define	NET_TRACE	0
#endif	NET_TRACE
#ifndef	NET_PRINT
#define	NET_PRINT	0
#endif	NET_PRINT


#define	LOCK_THREADS	0

#define	NM_STATISTICS	1

#define NM_USE_KDS	0

#define	USE_VMTP	0

#define	NETPORT		0

#define PORTSTAT	1

#define	RPCMOD		1

#define	USE_TCP		1

#define	CAMELOT		0

#define	COMPAT		0

#endif	_CONFIG_
