#
# Generic top-level makefile for simple commands
# (c) NeXT, Inc.  1987
#
CFLAGS=	-O -DNeXT_MOD -I../include -I/usr/include/arpa -DVMUNIX -DMXDOMAIN -DNeXT_NFS
IFLAGS= -s -c -o root -m 4551
LIBS= -ldbm

PRODUCT= sendmail
PROJECT= cmds

BINDIR=	/usr/lib
SRCDIR= /usr/src/${PROJECT}/ucb/${PRODUCT}/src

HFILES= conf.h sendmail.h dbm.h mailstats.h trace.h
YFILES=
CFILES= conf.c deliver.c main.c parseaddr.c err.c alias.c savemail.c \
	sysexits.c util.c bmove.c arpadate.c version.c collect.c \
	macro.c headers.c readcf.c stab.c recipient.c stats.c daemon.c \
	usersmtp.c srvrsmtp.c queue.c clock.c trace.c envelope.c \
	convtime.c remote.c domain.c
SFILES=

SRCS= ${HFILES} ${YFILES} ${CFILES} ${SFILES}
OBJS= ${CFILES:.c=.o} ${YFILES:.y=.o} ${SFILES:.s=.o}

FILES=	${SRCS} Makefile Makedep TODO
INTERMEDIATES=
DERIVED=
GARBAGE= TAGS tags vers.c

all:	${PRODUCT}

#
# Building PRODUCT
#

${PRODUCT}.NEW:	${OBJS} vers.o
	$(CC) $(CFLAGS) -o $@ ${OBJS} vers.o ${LIBS}

vers.c: ${DOVERS} ${OBJS}
	@rm -f $@
	vers_string -c ${PRODUCT} > $@


#
# Standard targets
#
${PRODUCT}:	.depend_done $$@.NEW

clean:	ALWAYS
	-rm -f *.o *.NEW
	-rm -f ${PRODUCT} ${DERIVED} ${INTERMEDIATES} ${GARBAGE}
	-rm -f Makedep .depend_done
	touch Makedep

install: DSTROOT ${DSTROOT}${BINDIR} all
	install ${IFLAGS} ${PRODUCT}.NEW ${DSTROOT}${BINDIR}/${PRODUCT}

local: LCLROOT ${LCLROOT}${BINDIR} all
	install ${IFLAGS} ${PRODUCT}.NEW ${LCLROOT}${BINDIR}/${PRODUCT}

installsrc: SRCROOT
	-rm -rf ${SRCROOT}${SRCDIR}
	mkdirs ${SRCROOT}${SRCDIR}
	cp ${FILES} ${SRCROOT}${SRCDIR}

DSTROOT LCLROOT SRCROOT:
	@if [ -n "${$@}" ]; \
	then \
		exit 0; \
	else \
		echo Must define $@; \
		exit 1; \
	fi

${DSTROOT}${BINDIR} ${LCLROOT}${BINDIR}:
	mkdirs $@

depend .depend_done: ${DERIVED}
	rm -f Makedep
	${CC} -M -I../include -I/usr/include/arpa ${CFILES} ${SFILES} ${DERIVED} | \
	    awk '{ if ($$1 != prev) { if (rec != "") print rec; \
		rec = $$0; prev = $$1; } \
		else { if (length(rec $$2) > 78) { print rec; rec = $$0; } \
		else rec = rec " " $$2 } } \
		END { print rec }' >Makedep
	-touch .depend_done


tags:	ALWAYS
	etags ${SRCS}
	ctags ${SRCS}

ALWAYS:

include Makedep
